### ISSUE TITLE
Lua-inspired gamedev language

### ISSUE THREAD

**Issue by erlend-sh** [Asmageddon/luashell#1]
Hey,

I’m unable to find any direct contact info for you so please excuse me for this inappropriate use of your issue tracker. I saw you commenting on the Lobster lang, so I figured you might be interested in a somewhat related development:

https://mun-lang.org/

They have a Discord channel where you can ask questions, which would be greatly appreciated.

**Comment by Asmageddon** [comment]
@erlend-sh Sadly, I've got enough awful mental health kinda stuff, that, alas, I don't really get to invest much interest in languages nowadays :-(

But thank you for reaching out, it is a nice surprise out of the blue. Fun fact, one of my best friends is also Erlend.

**Comment by erlend-sh** [comment]
Sorry to hear that, thanks for letting me know. Your mental health should certainly come first, so I wish you well in that pursuit. Give your friend a high five from me! ✋
